In [1]:
import torch

In [2]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [3]:
y=torch.tensor([1,2,3])

In [4]:
y

tensor([1, 2, 3])

In [6]:
x=torch.ones(5,requires_grad=True)

In [7]:
z=x+2

In [8]:
z

tensor([3., 3., 3., 3., 3.], grad_fn=<AddBackward0>)

In [11]:
z=z.mean()

In [12]:
z.backward()

In [13]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [14]:
x.grad

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])

In [16]:
torch.cuda.is_available()

False

In [17]:
y=z**2


In [18]:
y

tensor(9., grad_fn=<PowBackward0>)

In [19]:
z=x+2
y=z**2

In [20]:
y

tensor([9., 9., 9., 9., 9.], grad_fn=<PowBackward0>)

In [23]:
y=y.sum()
y.backward()

In [24]:
y

tensor(45., grad_fn=<SumBackward0>)

In [25]:
y

tensor(45., grad_fn=<SumBackward0>)

In [27]:
x.grad

tensor([6.2000, 6.2000, 6.2000, 6.2000, 6.2000])

In [34]:
theory="""Of course, the Master Algorithm has at least as many skeptics as it has proponents. Doubt is in order when something looks like a silver bullet. The
most determined resistance comes from machine learning’s perennial foe: knowledge engineering. According to its proponents, knowledge can’t be learned automatically; it must be programmed into the computer by human
experts. Sure, learners can extract some things from data, but nothing you’d
confuse with real knowledge. To knowledge engineers, big data is not the
new oil; it’s the new snake oil.
In the early days of AI, machine learning seemed like the obvious path
to computers with humanlike intelligence; Turing and others thought it was
the only plausible path. But then the knowledge engineers struck back, and
by 1970 machine learning was firmly on the back burner. For a moment in
the 1980s, it seemed like knowledge engineering was about to take over the
world, with companies and countries making massive investments in it. But
disappointment soon set in, and machine learning began its inexorable rise,
at first quietly, and then riding a roaring wave of data.
Despite machine learning’s successes, the knowledge engineers remain
unconvinced. They believe that its limitations will soon become apparent,
and the pendulum will swing back. Marvin Minsky, an MIT professor and
AI pioneer, is a prominent member of this camp. Minsky is not just
skeptical of machine learning as an alternative to knowledge engineering,
he’s skeptical of any unifying ideas in AI. Minsky’s theory of intelligence,
as expressed in his book The Society of Mind, could be unkindly
characterized as “the mind is just one damn thing after another.” The
Society of Mind is a laundry list of hundreds of separate ideas, each with its
own vignette. The problem with this approach to AI is that it doesn’t work;
it’s stamp collecting by computer. Without machine learning, the number of
ideas needed to build an intelligent agent is infinite. If a robot had all the
same capabilities as a human except learning, the human would soon leave
it in the dust.
Minsky was an ardent supporter of the Cyc project, the most notorious
failure in the history of AI. The goal of Cyc was to solve AI by entering
into a computer all the necessary knowledge. When the project began in the
1980s, its leader, Doug Lenat, confidently predicted success within a
decade. Thirty years later, Cyc continues to grow without end in sight, and
commonsense reasoning still eludes it. Ironically, Lenat has belatedly
embraced populating Cyc by mining the web, not because Cyc can read, but
because there’s no other way.
Even if by some miracle we managed to finish coding up all the
necessary pieces, our troubles would be just beginning. Over the years, a
number of research groups have attempted to build complete intelligent
agents by putting together algorithms for vision, speech recognition,
language understanding, reasoning, planning, navigation, manipulation, and
so on. Without a unifying framework, these attempts soon hit an
insurmountable wall of complexity: too many moving parts, too many
interactions, too many bugs for poor human software engineers to cope
with. Knowledge engineers believe AI is just an engineering problem, but
we have not yet reached the point where engineering can take us the rest of
the way. In 1962, when Kennedy gave his famous moon-shot speech, going
to the moon was an engineering problem. In 1662, it wasn’t, and that’s
closer to where AI is today.
In industry, there’s no sign that knowledge engineering will ever be able
to compete with machine learning outside of a few niche areas. Why pay
experts to slowly and painfully encode knowledge into a form computers
can understand, when you can extract it from data at a fraction of the cost?
What about all the things the experts don’t know but you can discover from
data? And when data is not available, the cost of knowledge engineering
seldom exceeds the benefit. Imagine if farmers had to engineer each
cornstalk in turn, instead of sowing the seeds and letting them grow: we
would all starve.
Another prominent machine-learning skeptic is the linguist Noam
Chomsky. Chomsky believes that language must be innate, because the
examples of grammatical sentences children hear are not enough to learn a
grammar. This only puts the burden of learning language on evolution,
however; it does not argue against the Master Algorithm but only against it
being something like the brain. Moreover, if a universal grammar exists (as
Chomsky believes), elucidating it is a step toward elucidating the Master
Algorithm. The only way this is not the case is if language has nothing in
common with other cognitive abilities, which is implausible given its
evolutionary recency.
In any case, if we formalize Chomsky’s “poverty of the stimulus”
argument, we find that it’s demonstrably false. In 1969, J. J. Horning
proved that probabilistic context-free grammars can be learned from
positive examples only, and stronger results have followed. (Context-free
grammars are the linguist’s bread and butter, and the probabilistic version
models how likely each rule is to be used.) Besides, language learning
doesn’t happen in a vacuum; children get all sorts of cues from their parents
and the environment. If we’re able to learn language from a few years’
worth of examples, it’s partly because of the similarity between its structure
and the structure of the world. This common structure is what we’re
interested in, and we know from Horning and others that it suffices.
More generally, Chomsky is critical of all statistical learning. He has a
list of things statistical learners can’t do, but the list is fifty years out of
date. Chomsky seems to equate machine learning with behaviorism, where
animal behavior is reduced to associating responses with rewards. But
machine learning is not behaviorism. Modern learning algorithms can learn
rich internal representations, not just pairwise associations between stimuli.
In the end, the proof is in the pudding. Statistical language learners
work, and hand-engineered language systems don’t. The first eye-opener
came in the 1970s, when DARPA, the Pentagon’s research arm, organized
the first large-scale speech recognition project. To everyone’s surprise, a
simple sequential learner of the type Chomsky derided handily beat a
sophisticated knowledge-based system. Learners like it are now used in just
about every speech recognizer, including Siri. Fred Jelinek, head of the
speech group at IBM, famously quipped that “every time I fire a linguist,
the recognizer’s performance goes up.” Stuck in the knowledge-engineering
mire, computational linguistics had a near-death experience in the late
1980s. Since then, learning-based methods have swept the field, to the point
where it’s hard to find a paper devoid of learning in a computational
linguistics conference. Statistical parsers analyze language with accuracy
close to that of humans, where hand-coded ones lagged far behind. Machine
translation, spelling correction, part-of-speech tagging, word sense
disambiguation, question answering, dialogue, summarization: the best
systems in these areas all use learning. Watson, the Jeopardy! computer
champion, would not have been possible without it.
To this Chomsky might reply that engineering successes are not proof of
scientific validity. On the other hand, if your buildings collapse and your
engines don’t run, perhaps something is wrong with your theory of physics.
Chomsky thinks linguists should focus on “ideal” speaker-listeners, as
defined by him, and this gives him license to ignore things like the need for
statistics in language learning. Perhaps it’s not surprising, then, that few
experimentalists take his theories seriously any more.
Another potential source of objections to the Master Algorithm is the
notion, popularized by the psychologist Jerry Fodor, that the mind is
composed of a set of modules with only limited communication between
them. For example, when you watch TV your “higher brain” knows that it’s
only light flickering on a flat surface, but your visual system still sees threedimensional shapes. Even if we believe in the modularity of mind, however,
that does not imply that different modules use different learning algorithms.
The same algorithm operating on, say, visual and verbal information may
suffice.
Critics like Minsky, Chomsky, and Fodor once had the upper hand, but
thankfully their influence has waned. Nevertheless, we should keep their
criticisms in mind as we set out on the road to the Master Algorithm for two
reasons. The first is that knowledge engineers faced many of the same
problems machine learners do, and even if they didn’t succeed, they learned
many valuable lessons. The second is that learning and knowledge are
intertwined in surprisingly subtle ways, as we’ll soon find out.
Unfortunately, the two camps often talk past each other. They speak
different languages: machine learning speaks probability, and knowledge
engineering speaks logic. Later in the book we’ll see what to do about this.
"""

In [35]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import  Tokenizer

In [36]:
tokenizer=Tokenizer()

In [37]:
tokenizer.fit_on_texts([theory])

In [81]:
(tokenizer.word_index)

{'the': 1,
 'of': 2,
 'in': 3,
 'to': 4,
 'is': 5,
 'a': 6,
 'and': 7,
 'learning': 8,
 'knowledge': 9,
 'that': 10,
 'it': 11,
 'machine': 12,
 'not': 13,
 'with': 14,
 'engineering': 15,
 'but': 16,
 'as': 17,
 'if': 18,
 'language': 19,
 'by': 20,
 'we': 21,
 'chomsky': 22,
 'from': 23,
 'be': 24,
 'can': 25,
 'ai': 26,
 'on': 27,
 'this': 28,
 'all': 29,
 'when': 30,
 'like': 31,
 'its': 32,
 'it’s': 33,
 'only': 34,
 'an': 35,
 'algorithm': 36,
 'has': 37,
 'many': 38,
 'data': 39,
 'engineers': 40,
 'was': 41,
 'for': 42,
 'just': 43,
 'mind': 44,
 'speech': 45,
 'master': 46,
 'learners': 47,
 'soon': 48,
 'cyc': 49,
 'have': 50,
 'where': 51,
 'are': 52,
 'your': 53,
 'at': 54,
 'computer': 55,
 'human': 56,
 'things': 57,
 'then': 58,
 'about': 59,
 'first': 60,
 'they': 61,
 'minsky': 62,
 'each': 63,
 'without': 64,
 'had': 65,
 'would': 66,
 'because': 67,
 'other': 68,
 'statistical': 69,
 'hand': 70,
 'something': 71,
 'learned': 72,
 'into': 73,
 'experts': 74,
 'back': 

In [39]:
len(tokenizer.word_index)

637

In [58]:
input_sent=[]
sentences = theory.split('. ')
for sentence in sentences:
    sent=sentence.strip() + '.'
    tokenized_sentence= tokenizer.texts_to_sequences([sent])[0]
    for i in range(1,len(tokenized_sentence)):
        input_sent.append(tokenized_sentence[:i+1])
    print(tokenized_sentence)
    

[2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11, 37, 107]
[197, 5, 3, 198, 30, 71, 199, 31, 6, 200, 201]
[1, 108, 202, 203, 204, 23, 12, 109, 205, 206, 9, 15]
[207, 4, 32, 107, 9, 110, 24, 72, 208, 11, 111, 24, 209, 73, 1, 55, 20, 56, 74]
[210, 47, 25, 112, 113, 57, 23, 39, 16, 114, 211, 212, 14, 213, 9]
[4, 9, 40, 214, 39, 5, 13, 1, 115, 116, 33, 1, 115, 215, 116, 3, 1, 216, 217, 2, 26, 12, 8, 117, 31, 1, 218, 118, 4, 119, 14, 219, 120, 220, 7, 121, 221, 11, 41, 1, 34, 222, 118]
[16, 58, 1, 9, 40, 223, 75, 7, 20, 224, 12, 8, 41, 225, 27, 1, 75, 226]
[42, 6, 227, 3, 1, 76, 11, 117, 31, 9, 15, 41, 59, 4, 77, 122, 1, 123, 14, 228, 7, 229, 230, 231, 232, 3, 11]
[16, 233, 48, 78, 3, 7, 12, 8, 124, 32, 234, 235, 54, 60, 236, 7, 58, 237, 6, 238, 239, 2, 39, 240, 12, 109, 125, 1, 9, 40, 241, 242]
[61, 79, 10, 32, 243, 80, 48, 244, 245, 7, 1, 246, 80, 247, 75]
[248, 62, 35, 249, 250, 7, 26, 251, 5, 6, 126, 252, 2, 28, 253]
[62, 5, 13, 43, 127, 2, 12, 8, 17, 35, 254, 4, 9, 15, 255, 127, 2,

In [56]:
input_sent

[]

In [42]:
theory.split('\n')

['Of course, the Master Algorithm has at least as many skeptics as it has proponents. Doubt is in order when something looks like a silver bullet. The',
 'most determined resistance comes from machine learning’s perennial foe: knowledge engineering. According to its proponents, knowledge can’t be learned automatically; it must be programmed into the computer by human',
 'experts. Sure, learners can extract some things from data, but nothing you’d',
 'confuse with real knowledge. To knowledge engineers, big data is not the',
 'new oil; it’s the new snake oil.',
 'In the early days of AI, machine learning seemed like the obvious path',
 'to computers with humanlike intelligence; Turing and others thought it was',
 'the only plausible path. But then the knowledge engineers struck back, and',
 'by 1970 machine learning was firmly on the back burner. For a moment in',
 'the 1980s, it seemed like knowledge engineering was about to take over the',
 'world, with companies and countries making 

In [59]:
input_sent

[[2, 194],
 [2, 194, 1],
 [2, 194, 1, 46],
 [2, 194, 1, 46, 36],
 [2, 194, 1, 46, 36, 37],
 [2, 194, 1, 46, 36, 37, 54],
 [2, 194, 1, 46, 36, 37, 54, 195],
 [2, 194, 1, 46, 36, 37, 54, 195, 17],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11, 37],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11, 37, 107],
 [197, 5],
 [197, 5, 3],
 [197, 5, 3, 198],
 [197, 5, 3, 198, 30],
 [197, 5, 3, 198, 30, 71],
 [197, 5, 3, 198, 30, 71, 199],
 [197, 5, 3, 198, 30, 71, 199, 31],
 [197, 5, 3, 198, 30, 71, 199, 31, 6],
 [197, 5, 3, 198, 30, 71, 199, 31, 6, 200],
 [197, 5, 3, 198, 30, 71, 199, 31, 6, 200, 201],
 [1, 108],
 [1, 108, 202],
 [1, 108, 202, 203],
 [1, 108, 202, 203, 204],
 [1, 108, 202, 203, 204, 23],
 [1, 108, 202, 203, 204, 23, 12],
 [1, 108, 202, 203, 204, 23, 12, 109],
 [1, 108, 

In [60]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
new_input_sent=pad_sequences(input_sent)

In [62]:
new_input_sent.shape

(1406, 58)

In [63]:
input_sent

[[2, 194],
 [2, 194, 1],
 [2, 194, 1, 46],
 [2, 194, 1, 46, 36],
 [2, 194, 1, 46, 36, 37],
 [2, 194, 1, 46, 36, 37, 54],
 [2, 194, 1, 46, 36, 37, 54, 195],
 [2, 194, 1, 46, 36, 37, 54, 195, 17],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11, 37],
 [2, 194, 1, 46, 36, 37, 54, 195, 17, 38, 196, 17, 11, 37, 107],
 [197, 5],
 [197, 5, 3],
 [197, 5, 3, 198],
 [197, 5, 3, 198, 30],
 [197, 5, 3, 198, 30, 71],
 [197, 5, 3, 198, 30, 71, 199],
 [197, 5, 3, 198, 30, 71, 199, 31],
 [197, 5, 3, 198, 30, 71, 199, 31, 6],
 [197, 5, 3, 198, 30, 71, 199, 31, 6, 200],
 [197, 5, 3, 198, 30, 71, 199, 31, 6, 200, 201],
 [1, 108],
 [1, 108, 202],
 [1, 108, 202, 203],
 [1, 108, 202, 203, 204],
 [1, 108, 202, 203, 204, 23],
 [1, 108, 202, 203, 204, 23, 12],
 [1, 108, 202, 203, 204, 23, 12, 109],
 [1, 108, 

In [68]:
max([len(x) for x in input_sent])

58

In [69]:
new_input_sent

array([[  0,   0,   0, ...,   0,   2, 194],
       [  0,   0,   0, ...,   2, 194,   1],
       [  0,   0,   0, ..., 194,   1,  46],
       ...,
       [  0,   0,   0, ...,  96,   4, 104],
       [  0,   0,   0, ...,   4, 104,  59],
       [  0,   0,   0, ..., 104,  59,  28]])

In [72]:
x=new_input_sent[:,1:57]

In [94]:
x.shape

(1406, 56)

In [76]:
y=new_input_sent[:,-1]

In [77]:
y

array([194,   1,  46, ..., 104,  59,  28])

In [78]:
x.shape

(1406, 56)

In [79]:
y.shape

(1406,)

In [82]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=638)

In [83]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [85]:
model=Sequential()

model.add(Embedding(638, 100, input_length=56))
model.add(LSTM(200))

model.add(Dense(638, activation='softmax'))

In [86]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [87]:
model.fit(x,y,epochs=1)

Epoch 1/100
44/44 [==============================] - 7s 119ms/step - loss: 6.2582 - accuracy: 0.0455
Epoch 2/100
44/44 [==============================] - 5s 118ms/step - loss: 5.8886 - accuracy: 0.0583
Epoch 3/100
44/44 [==============================] - 5s 123ms/step - loss: 5.8118 - accuracy: 0.0583
Epoch 4/100
44/44 [==============================] - 5s 118ms/step - loss: 5.7558 - accuracy: 0.0583
Epoch 5/100
44/44 [==============================] - 5s 121ms/step - loss: 5.6754 - accuracy: 0.0583
Epoch 6/100
44/44 [==============================] - 5s 119ms/step - loss: 5.5724 - accuracy: 0.0633
Epoch 7/100
44/44 [==============================] - 5s 119ms/step - loss: 5.4427 - accuracy: 0.0718
Epoch 8/100
44/44 [==============================] - 5s 120ms/step - loss: 5.2937 - accuracy: 0.0825
Epoch 9/100
44/44 [==============================] - 5s 115ms/step - loss: 5.1046 - accuracy: 0.0925
Epoch 10/100
44/44 [==============================] - 5s 117ms/step - loss: 4.8846 - accura

In [99]:
import time
import numpy as np
text = "I love "

for i in range(25):
              
  # tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
    padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
    pos = np.argmax(model.predict(padded_token_text))
    for word,index in tokenizer.word_index.items():
         if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)

1/1 [==============================] - 0s 31ms/step
I love  pay
1/1 [==============================] - 0s 32ms/step
I love  pay experts
1/1 [==============================] - 0s 35ms/step
I love  pay experts to
1/1 [==============================] - 0s 32ms/step
I love  pay experts to slowly
1/1 [==============================] - 0s 31ms/step
I love  pay experts to slowly and
1/1 [==============================] - 0s 35ms/step
I love  pay experts to slowly and painfully
1/1 [==============================] - 0s 32ms/step
I love  pay experts to slowly and painfully encode
1/1 [==============================] - 0s 41ms/step
I love  pay experts to slowly and painfully encode knowledge
1/1 [==============================] - 0s 31ms/step
I love  pay experts to slowly and painfully encode knowledge into
1/1 [==============================] - 0s 32ms/step
I love  pay experts to slowly and painfully encode knowledge into a
1/1 [==============================] - 0s 31ms/step
I love  pay experts